name: unit363-web-vuln-lab

services:
  blog-insecure:
    build: ./insecure_blog
    container_name: insecure-blog
    ports:
      - "36301:36301"    # host:container

  evil-page:
    build: ./evil_page
    container_name: evil_page
    ports:
      - "63601:63601"    # host:container